### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [VickaMarkina/tinyone#1]
В CSS / HTML / JS не принято использование _ для именовании классов / идентификаторов / переменных.
Подчеркивание, как стиль именования, используется в переменных языка PHP.
Используйте методологию БЭМ, которая была разобрана в классе + есть описание в презентации + отдельный урок по ссылке в документации с разбором возможных ошибок.
Справочник https://ru.bem.info/methodology/quick-start/

![image](https://user-images.githubusercontent.com/8464662/144294353-1bed15e0-0cbb-4683-b302-6f4d731e1854.png)

**Comment by VickaMarkina** [comment]
Исправила.

**Comment by Alecto** [comment]
2 ссылки пожалуйста

чт, 2 груд. 2021 о 11:02 VickaMarkina ***@***.***> пише:

**Comment by VickaMarkina** [comment]
https://github.com/VickaMarkina/tinyone
https://vickamarkina.github.io/tinyone/

**Comment by Alecto** [comment]
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/144419200-27294b3e-d136-4254-9586-98a523c9baff.png)

**Comment by VickaMarkina** [comment]
https://vickamarkina.github.io/tinyone/
https://github.com/VickaMarkina/tinyone

Исправила. Не заменило SCSS файл, когда редактировала по БЭМ

**Comment by Alecto** [comment]
Теперь правильно, больше ошибок и замечаний нет.
Работа принята.

чт, 2 груд. 2021 о 14:18 VickaMarkina ***@***.***> пише:
